#########
# POST test
POST https://glowing-invention-9qvp6w79w79c7x44-3000.app.github.dev/api/sigmacharts/createTestPost HTTP/1.1
content-type: application/json

{
    "token": "xxx",
    "user": "xxx",
    "message": "RAM device alert. Check alarm logs at https://py-remote-mon-dept-tarcinfo.apps.cloudapps.unc.edu."
}

#########
# Simple get request
GET https://glowing-invention-9qvp6w79w79c7x44-3000.app.github.dev/api/sigmacharts/createTest1 HTTP/1.1
